#define STREAM_START                     1
#define STREAM_END                       2
#define VERSION_DIRECTIVE                3
#define BLOCK_MAPPING_START              4
#define BLOCK_END                        5
#define BLOCK_SEQUENCE_START             6
#define FLOW_SEQUENCE_START              7
#define SCALAR                           8
#define FLOW_SEQUENCE_END                9
#define FLOW_MAPPING_START              10
#define FLOW_MAPPING_END                11
#define VALUE                           12
#define KEY                             13
#define BLOCK_ENTRY                     14
#define TAG                             15
#define ANCHOR                          16
#define ALIAS                           17
#define FLOW_ENTRY                      18
