#define STREAM_START                     1
#define STREAM_END                       2
#define VERSION_DIRECTIVE                3
#define DOCUMENT_START                   4
#define DOCUMENT_END                     5
#define BLOCK_MAPPING_START              6
#define BLOCK_END                        7
#define BLOCK_SEQUENCE_START             8
#define FLOW_SEQUENCE_START              9
#define SCALAR                          10
#define FLOW_SEQUENCE_END               11
#define FLOW_MAPPING_START              12
#define FLOW_MAPPING_END                13
#define VALUE                           14
#define KEY                             15
#define BLOCK_ENTRY                     16
#define TAG                             17
#define ANCHOR                          18
#define ALIAS                           19
#define FLOW_ENTRY                      20
